title: "Ahmed Fouad — Tech & CI/CD Blog"
description: "Cloud, DevOps, and automation insights by Ahmed Fouad"
theme: minima

author:
  name: Ahmed Fouad
  linkedin: https://www.linkedin.com/in/ahmed-fouad-270200/
  upwork: https://www.upwork.com/freelancers/ahmedadminsolutions

# Enable automatic posts listing
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
